services:
  postgres:
    image: postgres:latest
    container_name: psql-barbergest
    restart: always
    ports:
      - ${DB_PORTS}
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
