//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.13

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "cash_register")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub opened_at: DateTime,
    pub closed_at: DateTime,
    pub initial_balance: Decimal,
    pub final_balance: Decimal,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
