//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.13

pub use super::appointments::Entity as Appointments;
pub use super::cash_register::Entity as CashRegister;
pub use super::client_appointments::Entity as ClientAppointments;
pub use super::clients::Entity as Clients;
pub use super::payments::Entity as Payments;
pub use super::products::Entity as Products;
pub use super::reports::Entity as Reports;
pub use super::services::Entity as Services;
pub use super::staff::Entity as Staff;
pub use super::user::Entity as User;
